import type { RewardQuest, TodayMission } from "./types";

const now = new Date();
const daysFromNow = (days: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() + days);
  return d.toISOString();
};
const daysAgo = (days: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - days);
  return d.toISOString();
};

export const MOCK_QUESTS: RewardQuest[] = [
  {
    id: "10L",
    type: "luxury",
    title: "10L Starter",
    subtitle: "Level 1",
    rewardDescription: "Tech gadget + travel voucher",
    icon: "sparkles",
    gradient: "rewards-hero-active",
    status: "in_progress",
    isActiveQuest: true,
    overallProgressPct: 72,
    primaryBlocker: "You need 1 more active team leg",
    nextAction: "Get 1 more active team leg",
    window: {
      startsAt: daysAgo(67),
      endsAt: daysFromNow(23),
      daysLeft: 23,
      expired: false,
      label: "90-day window",
    },
    keys: [
      {
        id: "team",
        label: "Team sales",
        current: 1000000,
        required: 1000000,
        unit: "INR",
        currentDisplay: "₹10.00L",
        requiredDisplay: "₹10.00L",
        remainingDisplay: "Done",
        progressPct: 100,
        status: "complete",
        helpText: "Total new-plan sales from your team. Max 50% from one leg.",
      },
      {
        id: "direct",
        label: "Your sales",
        current: 68000,
        required: 50000,
        unit: "INR",
        currentDisplay: "₹68,000",
        requiredDisplay: "₹50,000",
        remainingDisplay: "Done",
        progressPct: 100,
        status: "complete",
        helpText: "Sales from people you directly sponsored.",
      },
      {
        id: "legs",
        label: "Active teams",
        current: 1,
        required: 2,
        unit: "count",
        currentDisplay: "1",
        requiredDisplay: "2",
        remainingDisplay: "1 more leg",
        progressPct: 50,
        status: "in_progress",
        helpText: "Direct members with an active package above the minimum.",
        cta: { label: "Go to team", href: "/team" },
      },
    ],
  },
  {
    id: "30L",
    type: "luxury",
    title: "30L Mid",
    subtitle: "Level 2",
    rewardDescription: "Bike + travel voucher",
    icon: "trophy",
    gradient: "rewards-hero-tier-2",
    status: "locked",
    isActiveQuest: false,
    overallProgressPct: 34,
    primaryBlocker: "Need ₹20.20L more team sales",
    nextAction: "Build team sales to ₹30L",
    window: {
      startsAt: daysAgo(67),
      endsAt: daysFromNow(23),
      daysLeft: 23,
      expired: false,
      label: "90-day window",
    },
    keys: [
      {
        id: "team",
        label: "Team sales",
        current: 980000,
        required: 3000000,
        unit: "INR",
        currentDisplay: "₹9.80L",
        requiredDisplay: "₹30.00L",
        remainingDisplay: "₹20.20L more",
        progressPct: 33,
        status: "in_progress",
        helpText: "Total new-plan sales from your team. Max 50% from one leg.",
        cta: { label: "View team", href: "/team" },
      },
      {
        id: "direct",
        label: "Your sales",
        current: 68000,
        required: 150000,
        unit: "INR",
        currentDisplay: "₹68,000",
        requiredDisplay: "₹1.50L",
        remainingDisplay: "₹82,000 more",
        progressPct: 45,
        status: "in_progress",
        helpText: "Sales from people you directly sponsored.",
        cta: { label: "Add sales", href: "/wallet" },
      },
      {
        id: "legs",
        label: "Active teams",
        current: 1,
        required: 3,
        unit: "count",
        currentDisplay: "1",
        requiredDisplay: "3",
        remainingDisplay: "2 more legs",
        progressPct: 33,
        status: "in_progress",
        helpText: "Direct members with an active package above the minimum.",
        cta: { label: "Go to team", href: "/team" },
      },
    ],
  },
  {
    id: "50L",
    type: "luxury",
    title: "50L Elite",
    subtitle: "Level 3",
    rewardDescription: "Office setup + car reward",
    icon: "target",
    gradient: "rewards-hero-tier-3",
    status: "locked",
    isActiveQuest: false,
    overallProgressPct: 18,
    primaryBlocker: "Unlock 30L Mid first",
    nextAction: "Focus on 10L Starter for now",
    window: {
      startsAt: daysAgo(67),
      endsAt: daysFromNow(53),
      daysLeft: 53,
      expired: false,
      label: "120-day window",
    },
    keys: [
      {
        id: "team",
        label: "Team sales",
        current: 980000,
        required: 5000000,
        unit: "INR",
        currentDisplay: "₹9.80L",
        requiredDisplay: "₹50.00L",
        remainingDisplay: "₹40.20L more",
        progressPct: 20,
        status: "locked",
        helpText: "Total new-plan sales from your team.",
      },
      {
        id: "direct",
        label: "Your sales",
        current: 68000,
        required: 250000,
        unit: "INR",
        currentDisplay: "₹68,000",
        requiredDisplay: "₹2.50L",
        remainingDisplay: "₹1.82L more",
        progressPct: 27,
        status: "locked",
        helpText: "Sales from people you directly sponsored.",
      },
      {
        id: "legs",
        label: "Active teams",
        current: 1,
        required: 4,
        unit: "count",
        currentDisplay: "1",
        requiredDisplay: "4",
        remainingDisplay: "3 more legs",
        progressPct: 25,
        status: "locked",
        helpText: "Direct members with an active package above the minimum.",
      },
    ],
  },
  {
    id: "1CR",
    type: "luxury",
    title: "1CR Crown",
    subtitle: "Level 4",
    rewardDescription: "Luxury car + international trip",
    icon: "crown",
    gradient: "rewards-hero-tier-4",
    status: "locked",
    isActiveQuest: false,
    overallProgressPct: 8,
    primaryBlocker: "Highest tier — long-term goal",
    nextAction: "Complete lower tiers first",
    window: {
      startsAt: daysAgo(67),
      endsAt: daysFromNow(53),
      daysLeft: 53,
      expired: false,
      label: "120-day window",
    },
    keys: [
      {
        id: "team",
        label: "Team sales",
        current: 980000,
        required: 10000000,
        unit: "INR",
        currentDisplay: "₹9.80L",
        requiredDisplay: "₹1.00Cr",
        remainingDisplay: "₹90.20L more",
        progressPct: 10,
        status: "locked",
        helpText: "Total new-plan sales from your team.",
      },
      {
        id: "direct",
        label: "Your sales",
        current: 68000,
        required: 500000,
        unit: "INR",
        currentDisplay: "₹68,000",
        requiredDisplay: "₹5.00L",
        remainingDisplay: "₹4.32L more",
        progressPct: 14,
        status: "locked",
        helpText: "Sales from people you directly sponsored.",
      },
      {
        id: "legs",
        label: "Active teams",
        current: 1,
        required: 5,
        unit: "count",
        currentDisplay: "1",
        requiredDisplay: "5",
        remainingDisplay: "4 more legs",
        progressPct: 20,
        status: "locked",
        helpText: "Direct members with an active package above the minimum.",
      },
    ],
  },
  {
    id: "europe-trip-2026",
    type: "travel",
    title: "Europe Trip 2026",
    subtitle: "Travel quest",
    rewardDescription: "Paris, Amsterdam, Zurich, Rome & Switzerland",
    imageUrl: "/rewards/europe-trip-bg.png",
    icon: "plane",
    gradient: "rewards-hero-travel",
    status: "in_progress",
    isActiveQuest: false,
    overallProgressPct: 58,
    primaryBlocker: "Need ₹4.2L more team sales",
    nextAction: "Add ₹4.2L team sales for Europe trip",
    window: {
      startsAt: daysAgo(120),
      endsAt: daysFromNow(245),
      daysLeft: 245,
      expired: false,
      label: "Program ends Dec 2026",
    },
    keys: [
      {
        id: "self-sales",
        label: "Your sales",
        current: 420000,
        required: 500000,
        unit: "INR",
        currentDisplay: "₹4.20L",
        requiredDisplay: "₹5.00L",
        remainingDisplay: "₹80,000 more",
        progressPct: 84,
        status: "in_progress",
        helpText: "Your personal sales toward the trip tier.",
        cta: { label: "View wallet", href: "/wallet" },
      },
      {
        id: "team-sales",
        label: "Team sales",
        current: 1580000,
        required: 2000000,
        unit: "INR",
        currentDisplay: "₹15.80L",
        requiredDisplay: "₹20.00L",
        remainingDisplay: "₹4.20L more",
        progressPct: 79,
        status: "in_progress",
        helpText: "Combined team sales for the trip tier.",
        cta: { label: "View team", href: "/team" },
      },
      {
        id: "kyc",
        label: "ID verified",
        current: 0,
        required: 1,
        unit: "count",
        currentDisplay: "Not done",
        requiredDisplay: "Verified",
        remainingDisplay: "Complete KYC",
        progressPct: 0,
        status: "in_progress",
        helpText: "You must verify your ID before claiming any reward.",
        cta: { label: "Start KYC", href: "/kyc" },
      },
    ],
  },
  {
    id: "cruise-trip-2026",
    type: "travel",
    title: "Cruise Trip 2026",
    subtitle: "Travel quest",
    rewardDescription: "Vizag → Pondicherry → Chennai cruise",
    imageUrl: "/rewards/cruise-trip-bg.png",
    icon: "ship",
    gradient: "rewards-hero-travel-alt",
    status: "locked",
    isActiveQuest: false,
    overallProgressPct: 22,
    primaryBlocker: "Need ₹12L more team sales",
    nextAction: "Build team sales for cruise tier",
    window: {
      startsAt: daysAgo(120),
      endsAt: daysFromNow(245),
      daysLeft: 245,
      expired: false,
      label: "Program ends Dec 2026",
    },
    keys: [
      {
        id: "self-sales",
        label: "Your sales",
        current: 420000,
        required: 1000000,
        unit: "INR",
        currentDisplay: "₹4.20L",
        requiredDisplay: "₹10.00L",
        remainingDisplay: "₹5.80L more",
        progressPct: 42,
        status: "in_progress",
        helpText: "Your personal sales toward the cruise tier.",
        cta: { label: "View wallet", href: "/wallet" },
      },
      {
        id: "team-sales",
        label: "Team sales",
        current: 1580000,
        required: 5000000,
        unit: "INR",
        currentDisplay: "₹15.80L",
        requiredDisplay: "₹50.00L",
        remainingDisplay: "₹34.20L more",
        progressPct: 32,
        status: "in_progress",
        helpText: "Combined team sales for the cruise tier.",
        cta: { label: "View team", href: "/team" },
      },
      {
        id: "kyc",
        label: "ID verified",
        current: 0,
        required: 1,
        unit: "count",
        currentDisplay: "Not done",
        requiredDisplay: "Verified",
        remainingDisplay: "Complete KYC",
        progressPct: 0,
        status: "in_progress",
        helpText: "You must verify your ID before claiming any reward.",
        cta: { label: "Start KYC", href: "/kyc" },
      },
    ],
  },
];

export const MOCK_MISSIONS: TodayMission[] = [
  {
    id: "kyc",
    text: "Complete your ID verification to claim rewards",
    actionLabel: "Start KYC",
    href: "/kyc",
    priority: "urgent",
  },
  {
    id: "leg",
    text: "Get 1 more active team leg for 10L Starter",
    actionLabel: "Go to team",
    href: "/team",
    priority: "normal",
  },
  {
    id: "europe",
    text: "Add ₹80,000 more of your sales for Europe trip",
    actionLabel: "View wallet",
    href: "/wallet",
    priority: "normal",
  },
];

export function getActiveQuest(quests: RewardQuest[]): RewardQuest {
  return (
    quests.find((q) => q.isActiveQuest) ??
    quests.find((q) => q.status === "in_progress" || q.status === "claimable") ??
    quests[0]
  );
}

// Re-export helpers used by tests / story previews
export { getLuxuryQuests, getTravelQuests } from "./enrich-quests";
